version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: bash -c "yarn install && rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/self_analytics
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: $RAILS_ENV